#!/usr/bin/env bash

# Compile all of the files in ./assets/ from raw to C++ byte arrays

HEADER="./src/compiled-assets.h"

rm $HEADER -f

echo "// THIS FILE IS AUTOMATICALLY GENERATED! DO NOT MODIFY!" >> $HEADER
echo >> $HEADER
echo "// To regenerate this file, add your desired assets to ./assets and run " >> $HEADER
echo "// ./compile-assets.sh in the base directory of this project." >> $HEADER
echo >> $HEADER

for ASSET in ./assets/*; do
  echo "compiling $ASSET"
  xxd -i "$ASSET" >> "$HEADER"
done

echo "done!"
